sonar.organization=king-wealth247
sonar.projectKey=King-Wealth247_Automated-DevSecOps-Security-Gate
sonar.projectName=Automated DevSecOps Security Gate

sonar.sources=juice-shop
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
juice-shop/node_modules/**,\
juice-shop/build/**,\
juice-shop/dist/**,\
juice-shop/frontend/.angular/cache/**,\
juice-shop/test/**

sonar.tests=juice-shop/test

sonar.test.inclusions=\
juice-shop/test/**/*.test.ts,\
juice-shop/test/**/*.spec.ts

sonar.coverage.exclusions=\
juice-shop/test/**,\
juice-shop/**/*.test.ts,\
juice-shop/**/*.spec.ts